export const ENTIDADES_AUDITORIA = Object.freeze({
  PEDIDO: 'PEDIDO',
  CAJA: 'CAJA',
  STOCK: 'STOCK',
  USUARIO: 'USUARIO',
  PRODUCTO: 'PRODUCTO'
});

export const ACCIONES_AUDITORIA = Object.freeze({
  PEDIDO_ESTADO_CAMBIADO: 'PEDIDO_ESTADO_CAMBIADO',
  PEDIDO_CANCELADO: 'PEDIDO_CANCELADO',
  PEDIDO_COBRADO: 'PEDIDO_COBRADO',
  PEDIDO_COBRO_ANULADO: 'PEDIDO_COBRO_ANULADO',
  PEDIDO_CERRADO: 'PEDIDO_CERRADO',
  PEDIDO_DESCUENTO_APLICADO: 'PEDIDO_DESCUENTO_APLICADO',

  CAJA_ABIERTA: 'CAJA_ABIERTA',
  CAJA_CERRADA: 'CAJA_CERRADA',

  STOCK_MOVIMIENTO_MANUAL: 'STOCK_MOVIMIENTO_MANUAL',

  USUARIO_CREADO: 'USUARIO_CREADO',
  USUARIO_ACTUALIZADO: 'USUARIO_ACTUALIZADO',
  USUARIO_ESTADO_CAMBIADO: 'USUARIO_ESTADO_CAMBIADO',
  USUARIO_PASSWORD_CAMBIADO: 'USUARIO_PASSWORD_CAMBIADO',

  PRODUCTO_CREADO: 'PRODUCTO_CREADO',
  PRODUCTO_ACTUALIZADO: 'PRODUCTO_ACTUALIZADO',
  PRODUCTO_DISPONIBILIDAD_CAMBIADA: 'PRODUCTO_DISPONIBILIDAD_CAMBIADA',
  PRODUCTO_ELIMINADO: 'PRODUCTO_ELIMINADO',

  CATEGORIA_PRODUCTO_CREADA: 'CATEGORIA_PRODUCTO_CREADA',
  CATEGORIA_PRODUCTO_ELIMINADA: 'CATEGORIA_PRODUCTO_ELIMINADA'
});
