export const UNIDADES_INGREDIENTE = Object.freeze({
  GRAMO: 'G',
  KILOGRAMO: 'KG',
  MILILITRO: 'ML',
  LITRO: 'L',
  UNIDAD: 'UNIDAD'
});

export const TIPOS_MOVIMIENTO_STOCK = Object.freeze({
  ENTRADA: 'ENTRADA',
  SALIDA: 'SALIDA',
  AJUSTE: 'AJUSTE',
  MERMA: 'MERMA',
  CONSUMO: 'CONSUMO'
});

export const TIPOS_MOVIMIENTO_MANUAL = Object.freeze([
  TIPOS_MOVIMIENTO_STOCK.ENTRADA,
  TIPOS_MOVIMIENTO_STOCK.SALIDA,
  TIPOS_MOVIMIENTO_STOCK.AJUSTE,
  TIPOS_MOVIMIENTO_STOCK.MERMA
]);
